Rewritten the Pillow-SIMD readme
uploadcare/pillow-simd pull request #12
Opened 2016-10-07 11:54 UTC by dayton1987

Fixes # .

Changes proposed in this pull request:

 * 
 * 
 *

2016-10-07 13:42 UTC, homm requested changes

2016-10-07 13:42 UTC, homm commented on README.md
> +Pillow-SIMD is "following" the Pillow fork (which is a PIL's fork itself).
– fork
– the

2016-10-07 13:42 UTC, homm commented on README.md
> +Such examples are rather rare, though. It is also known, that certain processes might be optimized
cr

2016-10-07 13:42 UTC, homm commented on README.md
> +Currently, Pillow-SIMD can be [compiled](#installation) with SSE4 (default) and AVX2 support.
or

2016-10-07 13:42 UTC, homm commented on README.md
> +Pillow-SIMD project is production-ready for you to start building SIMD-enabled image processing systems.
–  for you to start building SIMD-enabled image processing systems

2016-10-07 13:42 UTC, homm commented on README.md
> +In fact, Uploadcare itself has been running Pillow-SIMD for about a year now.
– itself

2016-10-07 13:42 UTC, homm commented on README.md
> +In fact, Uploadcare itself has been running Pillow-SIMD for about a year now.
2 года

2016-10-07 13:42 UTC, homm commented on README.md
> +The following Uploadcare image operations are currently SIMD-accelerated:
– Uploadcare

2016-10-07 13:42 UTC, homm commented on README.md
> +The numbers represent processing rates in megapixels per second (Mpx/s).
(the more — the better)

2016-10-07 13:42 UTC, homm commented on README.md
> +Now, let's proceed to the numbers (the more — the better):
– – –

2016-10-07 13:42 UTC, homm commented on README.md
> +Here are the instruments we've been up to during the benchmarks:
the main idea is libs versions

2016-10-07 13:42 UTC, homm commented on README.md
> +The results show that Pillow is generally faster than ImageMagick,
revert to always

2016-10-07 13:42 UTC, homm commented on README.md
> +single-thread AVX2-enabled intel i5 4258U CPU.
Intel

2016-10-07 13:42 UTC, homm commented on README.md
> +For the benchmarking purposes, the radius was set to sigma × 2.5.
`sigma × 2.5`

2016-10-07 13:42 UTC, homm commented on README.md
> +Resampling for Pillow 2.7 was rewritten with minimal usage of floating point calculations,
– – –

2016-10-07 13:42 UTC, homm commented on README.md
> +Resampling for Pillow 2.7 was rewritten with minimal usage of floating point calculations,
and below

2016-10-07 13:42 UTC, homm commented on README.md
> +heavy loops unrolling, specific instructions, which aren't available for **scalar WTF**.
scalar data types

2016-10-07 13:42 UTC, homm commented on README.md
> +If there's a copy of the original Pillow installed, it has to be removed first.
```bash
$ pip uninstall -y pillow
```

2016-10-07 13:42 UTC, homm commented on README.md
> +In general, you need to run `pip install pillow-simd`,
In general, it's as simple as running `pip install pillow-simd`

2016-10-07 13:42 UTC, homm commented on README.md
> +The easiest way to do so is to define the `CC` variable **while -> during?** the compilation.
during — ok

2016-10-08 09:33 UTC, dayton1987 commented on README.md
> +Pillow-SIMD is "following" the Pillow fork (which is a PIL's fork itself).
done

2016-10-08 09:34 UTC, dayton1987 commented on README.md
> +Such examples are rather rare, though. It is also known, that certain processes might be optimized
done

2016-10-08 09:34 UTC, dayton1987 commented on README.md
> +Currently, Pillow-SIMD can be [compiled](#installation) with SSE4 (default) and AVX2 support.
corrected

2016-10-08 09:36 UTC, dayton1987 commented on README.md
> +Pillow-SIMD project is production-ready for you to start building SIMD-enabled image processing systems.
erased

2016-10-08 09:51 UTC, dayton1987 reviewed
Pillow-SIMD Review — Answered

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +In fact, Uploadcare itself has been running Pillow-SIMD for about a year now.
yup

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +The following Uploadcare image operations are currently SIMD-accelerated:
removed

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +The numbers represent processing rates in megapixels per second (Mpx/s).
reconfigured the paragraph

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +Here are the instruments we've been up to during the benchmarks:
+

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +Now, let's proceed to the numbers (the more — the better):
erased

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +The results show that Pillow is generally faster than ImageMagick,
reverted

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +single-thread AVX2-enabled intel i5 4258U CPU.
+

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +For the benchmarking purposes, the radius was set to sigma × 2.5.
transformed into a codeblock

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +Resampling for Pillow 2.7 was rewritten with minimal usage of floating point calculations,
dumped

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +heavy loops unrolling, specific instructions, which aren't available for **scalar WTF**.
fixed

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +In general, you need to run `pip install pillow-simd`,
Shouldn't it be `$ pip install pillow-simd` instead?

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +If there's a copy of the original Pillow installed, it has to be removed first.
fxied

2016-10-08 09:51 UTC, dayton1987 commented on README.md
> +The easiest way to do so is to define the `CC` variable **while -> during?** the compilation.
done

2016-10-13 13:30 UTC, homm approved these changes

2016-10-13 13:39 UTC, homm commented
Thanks!
Merged in https://github.com/uploadcare/pillow-simd/tree/simd/info

2016-10-13 13:39 UTC, closed without merging